version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflows/compute_LD_TWAS.wdl
    name: "TWAS_LD"
  - subclass: WDL 
    primaryDescriptorPath: /workflows/susie_TWAS.wdl
    name: "SusieTWAS"
